MySQL5Dialect: ''
datasource: ''
ddl-auto: ''
dialect: ''
driver-class-name: com.mysql.cj.jdbc.Driver
hibernate: ''
jpa: ''
org: ''
password: 1sT17CS068@
properties: ''
show-sql: ''
spring: ''
'true': ''
update: ''
url: jdbc:mysql://localhost:3306/EmployeeManagement
username: scg_indrajit
